build_catalog:
  script:
    - zypper addrepo https://download.opensuse.org/repositories/devel:languages:nodejs/SLE_12_SP5/devel:languages:nodejs.repo
    - zypper --non-interactive --no-gpg-checks refresh
    - zypper --non-interactive install go git nodejs14 npm helm jq podman nmap
    - YQ_URL="https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64"
    - curl -sLf ${YQ_URL} -o /usr/bin/yq && chmod +x /usr/bin/yq
    - usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(id -nu)
    - podman info
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      PACKAGE_VERSION=$(jq -r .version ./package.json)
      PACKAGE_NAME=$(jq -r .name ./package.json)
      IMAGE=$REGISTRY/$IMAGE_NAME/ui-extension-$PACKAGE_NAME

      readarray -t VERSIONS < <(podman search $IMAGE --list-tags --format="{{.Tag}}")

      echo -e "Checking releases for version: ${PACKAGE_VERSION}"
      for version in "${VERSIONS[@]}"; do
        if [[ ${version} == ${PACKAGE_VERSION} ]]; then
          echo "Package version has not been updated, skipping build."
          exit 1
        fi
      done
    - npm install -g --unsafe-perm yarn
    - yarn
    - ./scripts/publish -cl -r $REGISTRY -o $IMAGE_NAME
    - podman push `podman images -f reference!=registry.suse.com/bci/bci-base --format "{{index .Names 0}}"`
    - podman logout $CI_REGISTRY
  tags:
    - linux
