build_and_release:
  stage: build_catalog
  script:
    - zypper addrepo https://download.opensuse.org/repositories/devel:languages:nodejs/SLE_12_SP5/devel:languages:nodejs.repo
    - zypper --non-interactive --no-gpg-checks refresh
    - zypper --non-interactive install go git nodejs14 npm helm jq podman nmap
    - YQ_URL="https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64"
    - curl -sLf ${YQ_URL} -o /usr/bin/yq && chmod +x /usr/bin/yq
    - usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(id -nu)
    - podman info
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      echo 'Checking for version collisions...'
      PACKAGE_VERSION=`jq -r .version package.json`
      PACKAGE_NAME=`jq -r .name package.json`

      readarray -t VERSIONS < <(podman search $CI_REGISTRY_IMAGE/ui-extension-$PACKAGE_NAME --list-tags --format {{.Tag}})

      echo -e "VERSIONS: ${VERSIONS}"
      echo -e "Package version: ${PACKAGE_VERSION}"
      for version in ${VERSIONS[@]}; do
        if [[ ${version} == ${PACKAGE_VERSION} ]]; then
          echo "Cannot overwrite production image version ${version} since it already exists."
          podman logout $CI_REGISTRY
          exit 1
        fi
      done
    - npm install -g --unsafe-perm yarn
    - yarn
    - ./scripts/publish -cl -r $REGISTRY -o $IMAGE_NAMESPACE
    - podman push `podman images -f reference!=registry.suse.com/bci/bci-base --format "{{index .Names 0}}"`
    - podman logout $CI_REGISTRY
  tags:
    - linux
